/* eslint-disable @next/next/no-sync-scripts */
'use client';

import React, { useCallback } from 'react';

import { CacheProvider, Link } from '@chakra-ui/next-js';
import { Flex, Text, Box, ChakraProvider } from '@chakra-ui/react';
import { hookstate } from '@hookstate/core';

import { Session } from '@/common/utilities/session';

import kilt_logo from './kilt_logo.svg';
import './globals.css';
import { SporranConnect } from './components/Buttons';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const sporranState = hookstate({});

function Logo(props: any) {
  return (
    <Box {...props}>
      <Text fontSize="lg" fontWeight="bold">
        Logo
      </Text>
    </Box>
  );
}

const MenuItem = ({ children, isLast, to = '/', ...rest }: any) => {
  return (
    <Text
      mb={{ base: isLast ? 0 : 8, sm: 0 }}
      mr={{ base: 0, sm: isLast ? 0 : 8 }}
      display="block"
      {...rest}
    >
      <Link href={to}>{children}</Link>
    </Text>
  );
};

const CloseIcon = () => (
  <svg width="24" viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg">
    <title>Close</title>
    <path
      fill="white"
      d="M9.00023 7.58599L13.9502 2.63599L15.3642 4.04999L10.4142 8.99999L15.3642 13.95L13.9502 15.364L9.00023 10.414L4.05023 15.364L2.63623 13.95L7.58623 8.99999L2.63623 4.04999L4.05023 2.63599L9.00023 7.58599Z"
    />
  </svg>
);

const MenuIcon = () => (
  <svg
    width="24px"
    viewBox="0 0 20 20"
    xmlns="http://www.w3.org/2000/svg"
    fill="white"
  >
    <title>Menu</title>
    <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
  </svg>
);

const Header = (props: any) => {
  const [show, setShow] = React.useState(false);
  const toggleMenu = () => setShow(!show);

  const handleConnect = useCallback((session: Session) => {
    sporranState.set(session);
  }, []);

  return (
    <Flex
      as="nav"
      align="center"
      justify="end"
      wrap="wrap"
      w="100%"
      mb={8}
      p={8}
      bg={['primary.500', 'primary.500', 'transparent', 'transparent']}
      color={['white', 'white', 'primary.700', 'primary.700']}
      {...props}
    >
      {/* <Flex align="center">
        <Logo
          w="100px"
          color={['white', 'white', 'primary.500', 'primary.500']}
        />
      </Flex> */}

      <Box display={{ base: 'block', md: 'none' }} onClick={toggleMenu}>
        {show ? <CloseIcon /> : <MenuIcon />}
      </Box>

      <Box
        display={{ base: show ? 'block' : 'none', md: 'block' }}
        flexBasis={{ base: '100%', md: 'auto' }}
      >
        <Flex
          align="center"
          justify={['center', 'space-between', 'flex-end', 'flex-end']}
          direction={['column', 'row', 'row', 'row']}
          pt={[4, 4, 0, 0]}
        >
          {/* <MenuItem to="/">Home</MenuItem>
          <MenuItem to="/how">How It works </MenuItem>
          <MenuItem to="/faetures">Features </MenuItem>
          <MenuItem to="/pricing">Pricing </MenuItem> */}
          <SporranConnect onConnect={handleConnect} />
        </Flex>
      </Box>
    </Flex>
  );
};

function Layout(props: any) {
  return (
    <Flex
      direction="column"
      align="center"
      maxW={{ xl: '1200px' }}
      m="0 auto"
      {...props}
    >
      <Header />
      {props.children}
    </Flex>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Peranto App</title>
        <script src="https://unpkg.com/nprogress@0.2.0/nprogress.js"></script>
        <link
          rel="stylesheet"
          href="https://unpkg.com/nprogress@0.2.0/nprogress.css"
        />
      </head>
      <body>
        <img
          src={kilt_logo.src}
          style={{ position: 'absolute', right: '1rem', top: '1rem' }}
        />
        <CacheProvider>
          <ChakraProvider>
            <Layout>{children}</Layout>
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
